# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
common: &common
  adapter: postgresql
  encoding: unicode
  reconnect: false
  pool: 30

development:
  <<: *common
  host: localhost
  database: nextgen_development
  username: vagrant
  password: vagrant
  
