development:
  secret_key_base: 'c8b805da48d26e494e73027b67605187992e6ecb406000c099a408dadf88903b596b58cd784768742be566e36745e2ae7b0ac2d6bf59403195eff229be948af7'
  aws_access_key_id: 'garbagekey' 
  aws_secret_access_key: 'asdfasdf'
  fog_directory: ''
  
test:
  secret_key_base: 'c8b805da48d26e494e73027b67605187992e6ecb406000c099a408dadf88903b596b58cd784768742be566e36745e2ae7b0ac2d6bf59403195eff229be948af7'
  aws_access_key_id: 'garbagekey' 
  aws_secret_access_key: 'asdfasdf'
  fog_directory: ''
 
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  fog_directory: <%= ENV['AWS_BUCKET'] %>

